package be.vives.fridgepal.food_create

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModelProviders
import androidx.navigation.fragment.findNavController
import be.vives.fridgepal.R
import be.vives.fridgepal.database.AppDatabase
import be.vives.fridgepal.database.FoodItem
import be.vives.fridgepal.databinding.FragmentFoodCreateBinding
import java.util.*

class FoodCreateFragment : Fragment() {

    private lateinit var binding : FragmentFoodCreateBinding
    private var selectedExpiryDate = Date() // huidige dag

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {
        
        // uitbreiding fragment met databinding: inflate met DataBindingUtil
        binding = DataBindingUtil.inflate(
            inflater, R.layout.fragment_food_create, container, false)

        val application = requireNotNull(this.activity).application

        // DAO meegeven aan ViewModel voor uitvoeren van queries op database
        val dataSource = AppDatabase.getInstance(application).FoodDao

        val viewModelFactory = FoodCreateViewModelFactory(dataSource, application)

        val foodCreateViewModel = ViewModelProviders.of(this, viewModelFactory)
            .get(FoodCreateViewModel::class.java)

        binding.foodCreateViewModel = foodCreateViewModel
        binding.setLifecycleOwner(this)

        binding.buttonCreate.setOnClickListener {
            if(checkFoodComplete()){ // controleer input velden voor aanmaak FoodItem
                foodCreateViewModel.setNewFoodItem(getFoodItemFromForm())
                foodCreateViewModel.saveFoodItem()
            } else{
                Toast.makeText(context, "Gelieve alle velden in te vullen", Toast.LENGTH_SHORT).show()
            }
        }

        foodCreateViewModel.navigateToOverview.observe(viewLifecycleOwner, { hasNavigated ->
            hasNavigated?.let{
                this.findNavController().navigate(R.id.action_foodCreateFragment_to_foodOverviewFragment)
                foodCreateViewModel.doneNavigating()
            }

        })

        // Listener voor calendarView (calendarView.date retourneert altijd datum van vandaag)
        binding.calendarExpiryDate.setOnDateChangeListener { view, year, month, dayOfMonth ->
            selectedExpiryDate = GregorianCalendar(year,month,dayOfMonth).time
        }

        return binding.root
    }

    private fun checkFoodComplete(): Boolean {
        val nameNotEmpty: Boolean = binding.editTextPersonName.text.isNotBlank()

        //TODO checks voor datum:
        // a) niet op dag in verleden (oplossing: minDate instellen? eventueel op currentDay +1)
        val dateNotEmpty: Boolean = true
        return (nameNotEmpty && dateNotEmpty)
    }

    private fun getFoodItemFromForm() : FoodItem {
        val foodItem = FoodItem(
            // foodId => autogenerated indien 0
            name = binding.editTextPersonName.text.toString(),
            expiryDate = selectedExpiryDate,
            expiryType = getExpiryType(),
        )
        return foodItem
    }

    // hulpfunctie: omzetting id expiryType naar string
    private fun getExpiryType(): String {
        when (binding.radioGroupType.checkedRadioButtonId){
            R.id.radioTHT -> return "THT"
            R.id.radioTGT -> return "TGT"
            else -> return ""
        }
    }

}